all:
	@echo '====all===='
	pwd;/home/wlad/Development/adt-bundle-linux/android-ndk-r9/ndk-build -j 4 -s
clean:
	@echo '====clean===='
	pwd;/home/wlad/Development/adt-bundle-linux/android-ndk-r9/ndk-build clean

.PHONY: clean
.PHONY: all
